import "server-only";

import { randomUUID } from "node:crypto";
import { mkdir, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { prisma } from "@/lib/db";

export const UPLOAD_DIR = path.join(process.cwd(), "uploads");
export const MAX_UPLOAD_BYTES = 50 * 1024 * 1024; // 50 MB

const ALLOWED_MIME_PREFIXES = ["image/", "video/", "audio/", "text/"];
const ALLOWED_MIME_TYPES = new Set([
  "application/pdf",
  "application/msword",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "application/vnd.ms-excel",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  "application/vnd.ms-powerpoint",
  "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  "application/zip",
]);

export class UploadError extends Error {}

function assertAllowed(file: File) {
  if (file.size > MAX_UPLOAD_BYTES) {
    throw new UploadError(
      `"${file.name}" is ${(file.size / 1024 / 1024).toFixed(1)} MB. The limit is ${MAX_UPLOAD_BYTES / 1024 / 1024} MB.`,
    );
  }
  const type = file.type || "application/octet-stream";
  const allowed =
    ALLOWED_MIME_TYPES.has(type) || ALLOWED_MIME_PREFIXES.some((p) => type.startsWith(p));
  if (!allowed) {
    throw new UploadError(`"${file.name}" is not an accepted file type (${type}).`);
  }
}

/** Strips any directory component so a crafted filename can't escape UPLOAD_DIR. */
function safeName(name: string) {
  return path.basename(name).replace(/[^\w.\- ]+/g, "_").slice(0, 180) || "upload";
}

/**
 * Writes a browser File to disk and records it. The stored name is random, so
 * files are never addressable by guessing a coach's filename.
 */
export async function storeUpload(file: File, opts: { submissionId?: string } = {}) {
  assertAllowed(file);
  await mkdir(UPLOAD_DIR, { recursive: true });

  const ext = path.extname(safeName(file.name)).slice(0, 12);
  const storedName = `${randomUUID()}${ext}`;
  const bytes = Buffer.from(await file.arrayBuffer());
  await writeFile(path.join(UPLOAD_DIR, storedName), bytes);

  return prisma.upload.create({
    data: {
      filename: safeName(file.name),
      storedName,
      mimeType: file.type || "application/octet-stream",
      size: bytes.byteLength,
      submissionId: opts.submissionId,
    },
  });
}

export async function deleteUpload(uploadId: string) {
  const upload = await prisma.upload.findUnique({ where: { id: uploadId } });
  if (!upload) return;
  await prisma.upload.delete({ where: { id: uploadId } });
  await unlink(path.join(UPLOAD_DIR, upload.storedName)).catch(() => {
    // Already gone; the row is what matters.
  });
}

export function absolutePathFor(storedName: string) {
  // storedName is generated by us (a UUID), but resolve defensively anyway.
  const resolved = path.resolve(UPLOAD_DIR, path.basename(storedName));
  if (!resolved.startsWith(UPLOAD_DIR)) {
    throw new UploadError("Invalid file path.");
  }
  return resolved;
}

export function formatBytes(bytes: number) {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(0)} KB`;
  return `${(bytes / 1024 / 1024).toFixed(1)} MB`;
}
